### ISSUE TITLE
Estimated Elo?

### ISSUE THREAD

**Issue by scs-ben** [lucasart/Demolito#112]
What is your engines estimated? I am the Head System Administrator for TCEC and we are looking to incorporate new chess engines that are in active development. http://tcec.chessdom.com

**Comment by scs-ben** [comment]
Can you compile a windows executable?

**Comment by lucasart** [comment]
can you have a look at the readme ? all your questions are answered there (executables, elo strength -> links to rating lists etc.)

**Comment by lucasart** [comment]
@scs-ben: good job on the new TCEC GUI. it's a lot better than the old one.

**Comment by scs-ben** [comment]
Thanks for taking the time to answer my questions. Would you be interested in competing in TCEC?

**Comment by lucasart** [comment]
yes, sure. i can prepare some windows compiles. just let me know when.

**Comment by scs-ben** [comment]
We'll be collecting updates/binaries in about 1 week.

**Comment by scs-ben** [comment]
Are you on Discord?

**Comment by lucasart** [comment]
No. I use Google Hangouts, Whatsapp, and Skype. How many chats does one need :)

**Comment by lucasart** [comment]
Windows compiles: http://talkchess.com/forum3/viewtopic.php?f=2&t=68845#p778418

**Comment by scs-ben** [comment]
If I type "go nodes 1" the program crashes. This is on an Intel server and I tried all 4 variants for Intel chips that are in that thread post.

**Comment by scs-ben** [comment]
I did this first and it worked:
`> position startpos
> ucinewgame
`
Apparently startpos isn't default?

**Comment by scs-ben** [comment]
Do you have an option for verbose logging?

**Comment by lucasart** [comment]
No logo, I'm afraid. At least no official one.

Hash > 4GB is not going to gain anything. Too much hash hurts more than it helps. I would recommend just using 4. I will have a look, but I can't even test, because I only have 8GB.

No logging option.

**Comment by scs-ben** [comment]
It's crashing for no apparent reason

**Comment by scs-ben** [comment]
I tried to manually make it crash but no luck

**Comment by scs-ben** [comment]
Ok, I found out:
using: setoption name Hash value 4096 (or any value)
followed by: ucinewgame crashes it

**Comment by lucasart** [comment]
Looks like yet another compiler/libc bug with mingw. Works for for me, on Linux of course, but also for Windows compiles running in Wine.

**Comment by lucasart** [comment]
I guess we have to fall back to 2048. I see no other option as I can't reproduce this compiler bug with Wine.

**Comment by scs-ben** [comment]
I think I tried 2048 without success. Setting hash at all seemed to make the engine crash on ucinewgame

On Nov 9, 2018, at 18:42, lucasart <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess we have to fall back to 2048. I see no other option as I can't reproduce this compiler bug with Wine.

**Comment by lucasart** [comment]
Are you using the tpoppins compile?

**Comment by scs-ben** [comment]
Not sure any more. I used several. Can you link it here?

On Nov 9, 2018, at 21:13, lucasart <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using the tpoppins compile?

**Comment by scs-ben** [comment]
Just updated. Seems to work with 16GB hash and plays better

On Nov 9, 2018, at 23:28, lucasart <notifications@github.com<mailto:notifications@github.com>> wrote:


https://www.mediafire.com/file/47jr2tfeg2ejlmz/demolito_20181029-tp.zip/file

**Comment by lucasart** [comment]
@scs-ben: You do realize that 16GB and 30'+10" are disproportionate. That's far too much hash. With hash, more is better up to a point, where more is not only useless, but even harmful. I'm pretty sure engines lose elo from 2GB to 16GB at this time control (all of them not just Demolito). I estimate 1-2GB to be the correct value for this time control.

**Comment by scs-ben** [comment]
Even on 43 cores? I will set your engine to 2GB of hash, this can’t be changed once the division actually starts in a few hours.

On Nov 12, 2018, at 05:31, lucasart <notifications@github.com<mailto:notifications@github.com>> wrote:


@scs-ben<https://github.com/scs-ben>: You do realize that 16GB and 30'+10" are disproportionate. That's far too much hash. With hash, more is better up to a point, where more is not only useless, but even harmful. I'm pretty sure engines lose elo from 2GB to 16GB at this time control (all of them not just Demolito). I estimate 1-2GB to be the correct value for this time control.

**Comment by lucasart** [comment]
Ah yes. I didn't think about the 43 cores. Indeed, that makes more sense.

**Comment by scs-ben** [comment]
Unfortunately the division has started and I’ve set it to 2GB
