### ISSUE TITLE
UCI Options for Hash and threads not working?

### ISSUE THREAD

**Issue by Spill-The-Tea** [lucasart/Demolito#137]
UCI Options are for Appearance only?

Setoption name Hash value # 
Setoption name threads value # 

It seems that the uci options are not actually setting the hash or threads via commands, but are rather constant and are only changed if changed directly in the uci.c file, and recompiling:

specifically line 35: u_int64_t uciHash = 2;

**Comment by lucasart** [comment]
you are mistaken. please have a look at how setoption token is parsed and treated in uci.c
