### ISSUE TITLE
possible 'array out of bounds' in eval.c

### ISSUE THREAD

**Issue by HansLoehle** [lucasart/Demolito#157]
I'm almost sure, idx will never reach 4096 but shouldn't there be a 4095 in the call to min?

sincerly, Hans

https://github.com/lucasart/Demolito/blob/c9a97942c7f661505c9d173302307c922cdc590c/src/eval.c#L226

**Comment by lucasart** [comment]
You're right! Thanks.

These bugs are the worst. Extremely rare, so very hard to reproduce. And completely non deterministic effects, or even worse, no effect (eg. my compiler/platform happens to generate padding at this memory adress, but another wont…)
