### ISSUE TITLE
I am really sorry but i need help

### ISSUE THREAD

**Issue by abdulbadii** [lucasart/Demolito#160]
I am really sorry but i need lucasart's/your help to assist finish Ethereal conversion to c++
https://github.com/abdulbadii/Ethereal_CPP/tree/master/src

I am really sorry again not in a proper place.. be lenient

**Comment by lucasart** [comment]
Sorry, but this is unrelated to Demolito, so closing the issue. I have no interest in your noob C++ "contribution" to Ethereal. And I hate C++, despite being quite well versed myself in this crap of a language (including the so called "modern" part of it).
