### ISSUE TITLE
set default compiler to clang in the makefile

### ISSUE THREAD

**Issue by AndyGrant** [lucasart/Demolito#164]
There are large OpenBench changes that have just been pushed, to allow for workers to be able to run just a subset of engines. IE, the worker will look for clang, gcc, g++, cargo, ... and only play workloads it can compile. As a result, I programmed a "tier list" for compilers. Demolito prefers clang. If clang is not found, and gcc is, then the make command will include ``CC=gcc``. You may change ``CC=clang`` back to normal.

**Comment by lucasart** [comment]
Thanks. Done.
