### ISSUE TITLE
Problems compiling on Raspberry Pi 32 bit

### ISSUE THREAD

**Issue by ScallyBag** [lucasart/Demolito#165]
Hi,

Your engine has been compiling fine up to and including the 27th of June, however after your recent code changes I get these errors both on Clang and GCC:

Al@PicoStretch:~/demolito/src $ make -j5
clang -march=native -std=gnu11 -DNDEBUG -O3 -flto -Wfatal-errors -Wall -Wextra -Wshadow -Wstrict-prototypes -Wsign-conversion -DVERSION=\"dev\" ./*.c -o demolito -s -lm -lpthread
./htable.c:23:8: fatal error: redefinition of 'HashCount' with a different type: 'size_t' (aka 'unsigned int') vs 'uint64_t' (aka 'unsigned long long')
size_t HashCount = 0;
       ^
./htable.h:30:17: note: previous declaration is here
extern uint64_t HashCount;
                ^
1 error generated.
./uci.c:32:10: fatal error: redefinition of 'uciHash' with a different type: 'uint64_t' (aka 'unsigned long long') vs 'size_t' (aka 'unsigned int')
uint64_t uciHash = 2;
         ^
./uci.h:18:15: note: previous declaration is here
extern size_t uciHash;
              ^
1 error generated.
makefile:18: recipe for target 'default' failed
make: *** [default] Error 1
Al@PicoStretch:~/demolito/src

Thanks,

Alan Cooper

**Comment by lucasart** [comment]
does this work ? 419f7ca5eba1d515756539d82ac96aead4d13a90

**Comment by ScallyBag** [comment]
That’s sorted out the problem.

Thank’s very much

Al.
