### ISSUE TITLE
Can't Compile with GCC

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [lucasart/Demolito#167]
Ran command: gcc * -o output

bitboard.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
eval.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
gen.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
In file included from htable.c:18:
platform.h:4:10: fatal error: pthread.h: No such file or directory
    4 | #include <pthread.h>
      |          ^~~~~~~~~~~
compilation terminated.
htable.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
In file included from main.c:20:
platform.h:4:10: fatal error: pthread.h: No such file or directory
    4 | #include <pthread.h>
      |          ^~~~~~~~~~~
compilation terminated.
platform.h:2:9: warning: #pragma once in main file
    2 | #pragma once
      |         ^~~~
platform.h:4:10: fatal error: pthread.h: No such file or directory
    4 | #include <pthread.h>
      |          ^~~~~~~~~~~
compilation terminated.
In file included from uci.h:16,
                 from position.c:21:
platform.h:4:10: fatal error: pthread.h: No such file or directory
    4 | #include <pthread.h>
      |          ^~~~~~~~~~~
compilation terminated.
position.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
pst.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
In file included from uci.h:16,
                 from search.c:22:
platform.h:4:10: fatal error: pthread.h: No such file or directory
    4 | #include <pthread.h>
      |          ^~~~~~~~~~~
compilation terminated.
search.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
sort.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
tune.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
types.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
In file included from uci.h:16,
                 from uci.c:25:
platform.h:4:10: fatal error: pthread.h: No such file or directory
    4 | #include <pthread.h>
      |          ^~~~~~~~~~~
compilation terminated.
uci.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
In file included from uci.h:16:
platform.h:4:10: fatal error: pthread.h: No such file or directory
    4 | #include <pthread.h>
      |          ^~~~~~~~~~~
compilation terminated.
util.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
workers.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
zobrist.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~

**Comment by lucasart** [comment]
RTFM
