### ISSUE TITLE
Can you build a Korean chess engine?

### ISSUE THREAD

**Issue by cjssh1002** [lucasart/Demolito#169]
Can you build a Korean chess engine?

**Comment by rchastain** [comment]
> Can you build a Korean chess engine?

Could you provide, please, a link to a reference document, where rules of Korean chess are explained?

It would be also interesting to have a document about notation of Korean chess in CECP and UCI protocols.

**Comment by rchastain** [comment]
Interesting article and comments here:
[https://www.chessvariants.com/oriental.dir/koreanchess.html](https://www.chessvariants.com/oriental.dir/koreanchess.html)

**Comment by cjssh1002** [comment]
We Koreans exactly need a Korean chess (Janggi) engine. Although it is not yet internationally famous, it is very popular in Korea just like Go(Baduk).
Chinese chess(Xiangqi) Many engines exist. similar to Korean chess However, in Korean chess(Janggi), only the fairy-stockfish engine exists.
So, if you develop it first, you can preempt it.
I'll give you a site you can refer to.
And I am a janggi player. So I can help you.
I've asked many programmers to develop it, but I've been rejected every time.

https://en.wikipedia.org/wiki/Janggi
https://www.pychess.org/variants/janggi
https://github.com/cutechess/cutechess/issues/564

I currently use Winboard GUI. I asked Winboard developer to develop janggi GUI, and he supported janggi.
  janggi uses the CECP protocol. This is because the Fairy-Stockfish Engine cannot use the UCI protocol on Winboard.

**Comment by cjssh1002** [comment]
It is difficult to build a janggi engine by yourself. But if you are interested in janggi engine development, I can test it and help with enough opinions and rules and tactics for janggi.
Think carefully, there are hundreds of chess engines in Western chess. So the competition is very fierce. In particular, the world's strongest stockfish engine exists. Korean chess is still an undeveloped area. If you're interested in Korean chess, that's very advanced thinking. Because it's a more interesting coding challenge.

Of course, Fairy Stockfish is a very powerful janggi engine. This is because NNUE evaluation is performed. However, if you develop a janggi specialized engine, it is competitive enough.

It is difficult to build a janggi engine by yourself. But if you are interested in janggi engine development, I can test it and help with enough opinions and rules and tactics for janggi.
Think carefully, there are hundreds of chess engines in Western chess. So the competition is very fierce. In particular, the world's strongest stockfish engine exists. Korean chess is still an undeveloped area. If you're interested in Korean chess, that's very advanced thinking. Because it's a more interesting coding challenge.

Of course, Fairy Stockfish is a very powerful janggi engine. This is because NNUE evaluation is performed. However, if you develop a janggi specialized engine, it is competitive enough.

fairy-stockfish "janggi engine" is written in bitboards. And it's 10x9.
This means janggi board and coordinates. There are two types.
UCI protocol and CECP protocol.
![23처](https://user-images.githubusercontent.com/63978900/167280211-a7b1360b-cf5d-41b5-933b-63b989d31bc0.PNG)
![12처](https://user-images.githubusercontent.com/63978900/167280212-099c5b6e-34b7-4c99-8578-71b4fa975947.PNG)

**Comment by lucasart** [comment]
not interested
