### ISSUE TITLE
draw detection

### ISSUE THREAD

**Issue by lucasart** [lucasart/Demolito#41]
1. done: 50 move rule
1. todo: insufficient material

**Comment by stockfishdeveloper** [comment]
Ok, I'm going to work on recognizing insufficient material. I'll open a pull request when I'm done. By the way, a quick going-over of the search routine did not seem to have LMR. If you can verify this, I'll add it.

**Comment by lucasart** [comment]
thanks.

**Comment by stockfishdeveloper** [comment]
OK

**Comment by stockfishdeveloper** [comment]
Alright, I did a rough draft of detecting insufficient material. It gives a score of 3 cp with KBvK and KNvK.
The diff is here: https://github.com/stockfishdeveloper/Demolito/compare/master...stockfishdeveloper:insufficient_material_detection
Note: According to FIDE rules, KNNK is automatically a draw. 
I'll open a pull request if you think this is good enough to commit.

**Comment by lucasart** [comment]
draw by chess rules should not be in the eval, but in the search. same as:
```
    if (ply > 0 && threadHistory[ThreadId].repetition(pos.rule50()))
        return DrawScore[us];
```
just need to extend it to include draw by insufficient material. best to make a wrapper function that handles all the cases: 3-rep, 50-move, insufficient material.

also, we should return the contempt score for draw by chess rules generally (3-rep, 50-move, insufficient material, stalemate). we don't want to special case and especially to hardcode (eg. -10, or -3 I see in your code).

**Comment by lucasart** [comment]
Also, what about KPK ? It's not a draw by chess rules. Of course it can sometimes be a draw by chess knowledge, but that's a different story (need a KPK bitbase).

**Comment by stockfishdeveloper** [comment]
I tried putting the draw detection just after the 50-move rule detection--it didn't work. 
I tried
`if(pos.insufficient_material())
`

**Comment by lucasart** [comment]
The root node cannot be game over by chess rules, including draw by chess rules. If that happens, the GUI is bogus. You can safely assume that it only happens at interior nodes, in which case, it may truncate the PV, but that's essentially correct.

**Comment by stockfishdeveloper** [comment]
OK. Makes sense
