### ISSUE TITLE
pawn eval

### ISSUE THREAD

**Issue by lucasart** [lucasart/Demolito#42]
- [x] isolated
- [x] chained
- [x] hole
- [x] passed
- [x] shield: didn't work.
- [x] pawn hash (per thread)

**Comment by stockfishdeveloper** [comment]
Why couldn't we implement a pawn hash? I could have it done in a day, maybe two.

**Comment by lucasart** [comment]
I never said there would be no pawn hash. Of course we need a pawn hash. But this needs to be done carflefully, and there are SMP issues to deal with. I'll do it eventually. One thing at a time: that's the key to success.

**Comment by stockfishdeveloper** [comment]
Ok, what's next on the list?

**Comment by lucasart** [comment]
killers, history, tt replacement policy, draw by insufficient material.

**Comment by stockfishdeveloper** [comment]
Ok, I'll have some work done to show you by tomorrow
