### ISSUE TITLE
Demolito Chess 

### ISSUE THREAD

**Issue by ChessGUI** [lucasart/Demolito#69]
Est-ce que le programme Demolito maintenant disponible à jouer dans le mode de tournoi 40 coups/ 20 minutes ou avec le délai de réflexion (par exemple 10 minutes) pour une partie d´échecs en tout?

cf. http://www.chess2u.com/t10684-demolito

**Comment by lucasart** [comment]
Yes, Demolito accepts (any combination of):
- fixed depth search
- fixed nodes search
- fixed time search
- time+increment clock
- tournament time control

**Comment by lucasart** [comment]
But you need to compile it from source. The link you provided is a compile from an old version that isn't going to work, as it only supports fixed time/depth/nodes (and it hundreds of elo behind).
