### ISSUE TITLE
cant compile on ubuntu 16.04

### ISSUE THREAD

**Issue by LocutusOfPenguin** [lucasart/Demolito#85]
Hi,
i got alot of missing errors like this:
bb_test - as an example - is only defined in H-file, but no code to find.

./make.sh 
/tmp/ccsDQCXK.ltrans0.ltrans.o: In Funktion `pos_move':
<artificial>:(.text+0x2a4): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x2bd): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x2de): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x365): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x390): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x406): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x412): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x4f6): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x682): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x68e): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x6d3): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x6df): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x750): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x75c): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x81b): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x82a): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x89a): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x8ad): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x91e): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x930): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x98b): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x999): Nicht definierter Verweis auf `bb_set'
/tmp/ccsDQCXK.ltrans0.ltrans.o: In Funktion `qsearch.lto_priv.28':
<artificial>:(.text+0xb04): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0xd33): Nicht definierter Verweis auf `bb_test'
/tmp/ccsDQCXK.ltrans1.ltrans.o: In Funktion `score_mobility':
<artificial>:(.text+0x1b0): Nicht definierter Verweis auf `bb_count'
/tmp/ccsDQCXK.ltrans1.ltrans.o: In Funktion `do_pawns':
<artificial>:(.text+0x2c1): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x2d0): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x326): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x3cf): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x41a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x476): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x48a): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x596): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x5d0): Nicht definierter Verweis auf `bb_test'
/tmp/ccsDQCXK.ltrans1.ltrans.o: In Funktion `evaluate':
<artificial>:(.text+0x7ea): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x7fc): Nicht definierter Verweis auf `KAttacks'
<artificial>:(.text+0x833): Nicht definierter Verweis auf `File'
<artificial>:(.text+0x843): Nicht definierter Verweis auf `bb_shift'
<artificial>:(.text+0x852): Nicht definierter Verweis auf `File'
<artificial>:(.text+0x860): Nicht definierter Verweis auf `bb_shift'
<artificial>:(.text+0x8c9): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x8d7): Nicht definierter Verweis auf `NAttacks'
<artificial>:(.text+0x939): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x948): Nicht definierter Verweis auf `bb_rattacks'
<artificial>:(.text+0x9c9): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x9d8): Nicht definierter Verweis auf `bb_battacks'
<artificial>:(.text+0xb6a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0xbad): Nicht definierter Verweis auf `bb_shift'
<artificial>:(.text+0xbd1): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0xc4a): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0xc5f): Nicht definierter Verweis auf `NAttacks'
<artificial>:(.text+0xc75): Nicht definierter Verweis auf `bb_battacks'
<artificial>:(.text+0xc8e): Nicht definierter Verweis auf `bb_rattacks'
<artificial>:(.text+0xca4): Nicht definierter Verweis auf `bb_battacks'
<artificial>:(.text+0xcb6): Nicht definierter Verweis auf `bb_rattacks'
<artificial>:(.text+0xd66): Nicht definierter Verweis auf `BPseudoAttacks'
<artificial>:(.text+0xd86): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0xd93): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0xdca): Nicht definierter Verweis auf `RPseudoAttacks'
<artificial>:(.text+0xde9): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0xdf6): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0xe89): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0xfa6): Nicht definierter Verweis auf `bb_several'
<artificial>:(.text+0x1076): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0x108c): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0x10c8): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0x10de): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0x10fa): Nicht definierter Verweis auf `bb_count'
/tmp/ccsDQCXK.ltrans1.ltrans.o:<artificial>:(.text+0x110e): Weitere nicht definierte Verweise auf `bb_count' folgen
/tmp/ccsDQCXK.ltrans1.ltrans.o: In Funktion `evaluate':
<artificial>:(.text+0x1299): Nicht definierter Verweis auf `File'
<artificial>:(.text+0x12a9): Nicht definierter Verweis auf `bb_shift'
/tmp/ccsDQCXK.ltrans2.ltrans.o: In Funktion `uci_loop':
<artificial>:(.text+0x9dc): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x9f6): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0xb63): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0xba4): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0xbb1): Nicht definierter Verweis auf `bb_msb'
<artificial>:(.text+0xbd7): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0xbe4): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0xc07): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0xc29): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0xcc6): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0xf5b): Nicht definierter Verweis auf `bb_msb'
/tmp/ccsDQCXK.ltrans3.ltrans.o: In Funktion `gen_pawn_moves':
<artificial>:(.text+0x9e): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0xd6): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0xfd): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text+0x10c): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x13a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x17b): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x1a6): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x1d2): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text+0x1dc): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x20a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x268): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x2aa): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x2be): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x2d8): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x30a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x332): Nicht definierter Verweis auf `bb_set'
/tmp/ccsDQCXK.ltrans3.ltrans.o: In Funktion `gen_piece_moves':
<artificial>:(.text+0x386): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x394): Nicht definierter Verweis auf `NAttacks'
<artificial>:(.text+0x3ba): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x3f6): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x408): Nicht definierter Verweis auf `bb_rattacks'
<artificial>:(.text+0x42a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x466): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x478): Nicht definierter Verweis auf `bb_battacks'
<artificial>:(.text+0x49a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x4d3): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x4e1): Nicht definierter Verweis auf `KAttacks'
<artificial>:(.text+0x50a): Nicht definierter Verweis auf `bb_pop_lsb'
/tmp/ccsDQCXK.ltrans3.ltrans.o: In Funktion `gen_check_escapes':
<artificial>:(.text+0x55a): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x568): Nicht definierter Verweis auf `KAttacks'
<artificial>:(.text+0x58a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x5a5): Nicht definierter Verweis auf `bb_several'
<artificial>:(.text+0x5c5): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x62b): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0x653): Nicht definierter Verweis auf `bb_set'
/tmp/ccsDQCXK.ltrans3.ltrans.o: In Funktion `gen_perft.part.1.lto_priv.21':
<artificial>:(.text+0x721): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x756): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x77d): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text+0x78c): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x7ba): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x7f4): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x836): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x85c): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text+0x86b): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x89a): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x904): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x95e): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0x96a): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0x976): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0x997): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x9c6): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0xa06): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0xa1a): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0xa38): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0xbc9): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0xc0e): Nicht definierter Verweis auf `bb_test'
/tmp/ccsDQCXK.ltrans4.ltrans.o: In Funktion `search.lto_priv.25':
<artificial>:(.text+0x1b4): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0x46d): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x5c6): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x614): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0xafd): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0xf11): Nicht definierter Verweis auf `bb_test'
/tmp/ccsDQCXK.ltrans4.ltrans.o:<artificial>:(.text+0x10ac): Weitere nicht definierte Verweise auf `bb_test' folgen
/tmp/ccsDQCXK.ltrans5.ltrans.o: In Funktion `finish.lto_priv.22':
<artificial>:(.text+0x2c): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x44): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x4e): Nicht definierter Verweis auf `KAttacks'
<artificial>:(.text+0x74): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x7e): Nicht definierter Verweis auf `NAttacks'
<artificial>:(.text+0x91): Nicht definierter Verweis auf `File'
<artificial>:(.text+0xb6): Nicht definierter Verweis auf `bb_shift'
<artificial>:(.text+0xc9): Nicht definierter Verweis auf `File'
<artificial>:(.text+0xdd): Nicht definierter Verweis auf `bb_shift'
<artificial>:(.text+0x124): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x12e): Nicht definierter Verweis auf `bb_rattacks'
<artificial>:(.text+0x164): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x16e): Nicht definierter Verweis auf `bb_battacks'
<artificial>:(.text+0x188): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x1ac): Nicht definierter Verweis auf `NAttacks'
<artificial>:(.text+0x1bb): Nicht definierter Verweis auf `KAttacks'
<artificial>:(.text+0x1d0): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text+0x1db): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text+0x1ec): Nicht definierter Verweis auf `bb_rattacks'
<artificial>:(.text+0x202): Nicht definierter Verweis auf `bb_battacks'
<artificial>:(.text+0x241): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x269): Nicht definierter Verweis auf `RPseudoAttacks'
<artificial>:(.text+0x271): Nicht definierter Verweis auf `BPseudoAttacks'
<artificial>:(.text+0x296): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x2b5): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0x2bf): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x2ca): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x2d4): Nicht definierter Verweis auf `bb_several'
<artificial>:(.text+0x314): Nicht definierter Verweis auf `bb_shift'
<artificial>:(.text+0x31b): Nicht definierter Verweis auf `File'
/tmp/ccsDQCXK.ltrans5.ltrans.o: In Funktion `move_see':
<artificial>:(.text+0x3b3): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x3cd): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x400): Nicht definierter Verweis auf `KAttacks'
<artificial>:(.text+0x41a): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text+0x422): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text+0x42d): Nicht definierter Verweis auf `NAttacks'
<artificial>:(.text+0x442): Nicht definierter Verweis auf `bb_rattacks'
<artificial>:(.text+0x463): Nicht definierter Verweis auf `bb_battacks'
<artificial>:(.text+0x52d): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x539): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x636): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x642): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x6c9): Nicht definierter Verweis auf `bb_clear'
/tmp/ccsDQCXK.ltrans5.ltrans.o: In Funktion `move_is_legal':
<artificial>:(.text+0x71a): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x72f): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x76b): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x793): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0x7a4): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x7c0): Nicht definierter Verweis auf `Ray'
<artificial>:(.text+0x7c5): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x7e7): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x81d): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x829): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x843): Nicht definierter Verweis auf `bb_clear'
<artificial>:(.text+0x854): Nicht definierter Verweis auf `bb_rattacks'
<artificial>:(.text+0x87b): Nicht definierter Verweis auf `bb_battacks'
/tmp/ccsDQCXK.ltrans5.ltrans.o: In Funktion `main':
<artificial>:(.text.startup+0x1a): Nicht definierter Verweis auf `bb_init'
<artificial>:(.text.startup+0x3ba): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text.startup+0x432): Nicht definierter Verweis auf `PAttacks'
<artificial>:(.text.startup+0x485): Nicht definierter Verweis auf `File'
<artificial>:(.text.startup+0x48c): Nicht definierter Verweis auf `File'
<artificial>:(.text.startup+0x4ae): Nicht definierter Verweis auf `File'
<artificial>:(.text.startup+0x4db): Nicht definierter Verweis auf `File'
<artificial>:(.text.startup+0x504): Nicht definierter Verweis auf `File'
/tmp/ccsDQCXK.ltrans5.ltrans.o:<artificial>:(.text.startup+0x515): Weitere nicht definierte Verweise auf `File' folgen
/tmp/ccsDQCXK.ltrans6.ltrans.o: In Funktion `search_go':
<artificial>:(.text+0x6f3): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x733): Nicht definierter Verweis auf `bb_test'
/tmp/ccsDQCXK.ltrans6.ltrans.o: In Funktion `sort_init':
<artificial>:(.text+0x837): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x87e): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x8dc): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0x8e8): Nicht definierter Verweis auf `Segment'
<artificial>:(.text+0x8f5): Nicht definierter Verweis auf `bb_count'
<artificial>:(.text+0x916): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x94a): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x981): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0xa6b): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0xbb8): Nicht definierter Verweis auf `Rank'
/tmp/ccsDQCXK.ltrans7.ltrans.o: In Funktion `pos_print.constprop.2':
<artificial>:(.text+0x80): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x96): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x11f): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x162): Nicht definierter Verweis auf `bb_test'
<artificial>:(.text+0x320): Nicht definierter Verweis auf `bb_pop_lsb'
<artificial>:(.text+0x354): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x375): Nicht definierter Verweis auf `Ray'
<artificial>:(.text+0x3a6): Nicht definierter Verweis auf `Ray'
<artificial>:(.text+0x3c6): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x3e7): Nicht definierter Verweis auf `Ray'
<artificial>:(.text+0x40b): Nicht definierter Verweis auf `Ray'
<artificial>:(.text+0x424): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x44a): Nicht definierter Verweis auf `Ray'
<artificial>:(.text+0x461): Nicht definierter Verweis auf `bb_msb'
<artificial>:(.text+0x485): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x4b6): Nicht definierter Verweis auf `Ray'
<artificial>:(.text+0x4ce): Nicht definierter Verweis auf `bb_msb'
/tmp/ccsDQCXK.ltrans7.ltrans.o: In Funktion `info_update.constprop.1':
<artificial>:(.text+0x7a5): Nicht definierter Verweis auf `bb_test'
/tmp/ccsDQCXK.ltrans8.ltrans.o: In Funktion `test':
<artificial>:(.text+0x315): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x356): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x362): Nicht definierter Verweis auf `bb_msb'
<artificial>:(.text+0x3c1): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x3dd): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x457): Nicht definierter Verweis auf `Rank'
<artificial>:(.text+0x463): Nicht definierter Verweis auf `bb_lsb'
<artificial>:(.text+0x489): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x4ad): Nicht definierter Verweis auf `bb_set'
<artificial>:(.text+0x556): Nicht definierter Verweis auf `bb_pop_lsb'
collect2: error: ld returned 1 exit status
./make.sh: Zeile 7: search: Befehl nicht gefunden

**Comment by lucasart** [comment]
you forgot the $1 argument of the make.sh script.

**Comment by LocutusOfPenguin** [comment]
sorry?
the problem are missing functions. What should i type to get it working?

**Comment by LocutusOfPenguin** [comment]
looks like y missing bitboard.c ? ...see tune branch? (wild guess)

**Comment by lucasart** [comment]
Please post minimal reproduction steps. Otherwise I can't help you.

**Comment by LocutusOfPenguin** [comment]
git clone https://github.com/lucasart/Demolito.git
Klone nach 'Demolito' ...
remote: Counting objects: 2793, done.
remote: Total 2793 (delta 0), reused 0 (delta 0), pack-reused 2793
Empfange Objekte: 100% (2793/2793), 533.56 KiB | 127.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (1875/1875), Fertig.
Prüfe Konnektivität ... Fertig.


 ./make.sh 1
./make.sh: Zeile 7: 1: Befehl nicht gefunden

 ./1
uci
id name Demolito 2017-10-01
id author lucasart
option name UCI_Chess960 type check default false
option name Hash type spin default 1 min 1 max 1048576
option name Threads type spin default 1 min 1 max 63
option name Contempt type spin default 10 min -100 max 100
option name Time Buffer type spin default 60 min 0 max 1000
uciok
go movetime 10
Speicherzugriffsfehler (Speicherabzug geschrieben)



Result:
So, there is a make problem on line 7 =command not found (i dont care now)
When i start the program fresh compiled it crushed after "go movetime" with a memory dump
The texts are in german, but i hope y can follow.

**Comment by LocutusOfPenguin** [comment]
and pls ignore the above messages  - you must have a bad impression - from me, hmm
They based on some git problem with not-checked out "bitboard.c" (dont know why this was happening).

Perhaps i should have opened a new issue. Sorry for disturb for that

**Comment by lucasart** [comment]
you cannot send an UCI go command without a prior ucinewgame. it's normal the the program will segfault. You need at least one ucinewgame before a go.

As you can see in `uci.c`, ucinewgame is where the hash table is resized (meaning allocated for the first time), and its content purged:
```
        else if (!strcmp(token, "ucinewgame")) {
            hash_resize(Hash);
            memset(HashTable, 0, Hash << 20);
```

**Comment by lucasart** [comment]
For the `1: Befehl nicht gefunden`, try using './' in front of the name, like this:
```
./make.sh ./demolito
```
If you just do `demolito` instead of `./demolito`, the command line interpreter will search the path, not the current directory.

**Comment by LocutusOfPenguin** [comment]
Thanks for yr help!
It works now.

For the "./" i would say the make.sh is not self-explaining. I dont know what its expects as parameter, although you probl call me a newbie :-)

Perhaps you can think about to update yr readme.md file for guys like me?


Concerning the "ucinewgame"
http://wbec-ridderkerk.nl/html/UCIProtocol.html saying:
"So the engine should not rely on this command even though all new GUIs should support it."

Other engines working in the way i used it - for this test.

**Comment by LocutusOfPenguin** [comment]
also your engine expects a "position startpos" otherwise it returns h8h8 (perhaps better 0000?).
Thats also different to other engines BUT here it seems ok as i now see:
* Before the engine is asked to search on a position, there will always be a position command
  to tell the engine about the current position.


Hitting <cr> also crushs it.


Whatever y think (about me), but i *HOPE* y agree with me that the program should never crush (two ways now) - maybe not work - nomatter what i type in. Thats the basic of uci to ignore all unknown's

**Comment by lucasart** [comment]
UCI is meant for machine to machine communication. That's why I assume input to be correct. I have no interest in making the code idiot proof with lots of safety nets and input validation code, or code to write self explanatory error messages when the user writes crap in the console. Sorry, this is not open for discussion. It's a design choice.

**Comment by LocutusOfPenguin** [comment]
Are y saying cause its M to M communication y dont need an(y) error-handling? Thats ridiculous.
After all thats written by users and they do make errors, including you.
I told y two things against the uci specification.
You should ignore(and not "crush"! by) bad user input, and y shouldnt rely on ucinewgame Both y can read in the docu i linked before. Noone asked y to write tons of code to handle all this (incl. error msg). This CR is a one liner.
And i said, that other uci engines behave different to yours (incl SF). I hoped y open minded to at least think about why thats so, instead of "i do my own way". I had no interest in discuss the pro/contras of uci with you. You are in charge of yr code, and you decide what to do with it.

If yr "error handling" is none, instead just crush, this disqualifies your program from include. Crush = BAD (by itself - nothing with uci at first place). Sorry, then yr "design choice" is not good - to be modest. There is no room for discussion either.

I never wanted to attack y. But im also not a beginner nor an idiot! Im in dev for lots of years incl. linux. So, from my program you wouldnt get this CR, but that not means, y shouldnt be prepared to ignore it. Sorry to hear, that you not interested to follow the uci specification.
