### ISSUE TITLE
Error en hanging

### ISSUE THREAD

**Issue by Coiled-Chess** [lucasart/Demolito#94]
Perdón por hablar en español.
En eval.c
La rutina static int hanging(const Position *pos, int us, bitboard_t attacks[NB_COLOR][NB_PIECE + 1])
linea 133: const int Hanging[] = {98, 64, 102, 181};
y
linea: 144: p = pos->pieceOn[bb_pop_lsb(&b)];

La variable: p esta entre los valores: 0 y 3. Con respecto al array Hanging[]
O entre 1 y 4.

PAWN = 0
KNIGHT = 1
BISHOP = 2
ROOK = 3
QUEEN = 4

Error:
Hanging[] = {98, 64, 102, 181};
por
Hanging[] = {0, 98, 64, 102, 181};

**Comment by lucasart** [comment]
Code is correct. See types.h. KNIGHT=0, …, QUEEN=3.
